
default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: sample_app_development
  username: postgres
  password: 0N1namak0
  host: localhost
  port: 5432

test:
  <<: *default
  database: sample_app_test
  username: postgres
  password: 0N1namak0
  host: localhost
  port: 5432

production:
  <<: *default
